vim_plugin_task "slim",       "git://github.com/bbommarito/vim-slim.git"
vim_plugin_task "jade",       "git://github.com/digitaltoad/vim-jade.git"
vim_plugin_task "robokai",    "git://github.com/vim-scripts/robokai.git"
vim_plugin_task "python",     "git://github.com/vim-scripts/python.vim.git"
vim_plugin_task "cocoa",      "git://github.com/msanders/cocoa.vim.git"
